export const dynamic = 'force-dynamic'
import { prisma } from '@/lib/prisma'
import { addGciEntry } from '@/app/actions'
import AdminGciActions from '@/app/components/AdminGciActions'

export default async function GciLedger() {
  const teamAgents = await prisma.agent.findMany({
    where: { role: 'TEAM_AGENT' },
    include: {
      showingPartners: true
    }
  })

  const gciEntries = await prisma.gciEntry.findMany({
    orderBy: { month: 'desc' },
    include: {
      teamAgent: true,
      sourceAgent: true
    }
  })

  // To properly handle the server action with bound parameters, we'll use a wrapper form action
  // We can't bind the teamAgentId ahead of time because it comes from the select dropdown.
  // Instead, we will update the addGciEntry action or create a wrapper that takes formData 
  // and extracts the teamAgentId from it.
  
  // Actually, wait, `addGciEntry` in `app/actions.ts` currently expects `teamAgentId` as the first argument,
  // and `formData` as the second. Let's create a wrapper function inside this component that acts as the action.
  const handleAddGci = async (formData: FormData) => {
    'use server'
    const teamAgentId = formData.get('teamAgentId') as string;
    // We can call the existing action
    await addGciEntry(teamAgentId, formData);
  }

  return (
    <div>
      <div style={{ marginBottom: '2rem' }}>
        <h1>GCI Ledger</h1>
        <p style={{ color: 'var(--text-secondary)', marginTop: '0.5rem' }}>Track and log Gross Commission Income for all Team Agents.</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '350px 1fr', gap: '2rem' }}>
        <div>
          <div className="card">
            <h2 style={{ marginBottom: '1.5rem', fontSize: '1.25rem' }}>Log Monthly GCI</h2>
            <form action={handleAddGci} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div>
                <label className="label" htmlFor="teamAgentId">Team Agent</label>
                <select id="teamAgentId" name="teamAgentId" className="input" required>
                  <option value="">Select a Team Agent...</option>
                  {teamAgents.map(agent => (
                    <option key={agent.id} value={agent.id}>{agent.name}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="label" htmlFor="month">Month</label>
                <input type="month" id="month" name="month" className="input" required defaultValue={new Date().toISOString().substring(0, 7)} />
              </div>

              <div>
                <label className="label" htmlFor="amount">Gross GCI Generated ($)</label>
                <input type="number" id="amount" name="amount" className="input" required step="0.01" placeholder="5000.00" />
              </div>
              
              <div>
                <label className="label" htmlFor="sourceAgentId">Source Agent (Optional)</label>
                <select id="sourceAgentId" name="sourceAgentId" className="input">
                  <option value="">None (General GCI)</option>
                  {teamAgents.flatMap(agent => 
                    agent.showingPartners.map(sp => (
                      <option key={sp.id} value={sp.id}>{sp.name} (under {agent.name})</option>
                    ))
                  )}
                </select>
                <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginTop: '0.25rem' }}>If this GCI was generated by a specific graduated showing partner.</p>
              </div>

              <button type="submit" className="btn" style={{ marginTop: '0.5rem' }}>Log GCI</button>
            </form>
          </div>
        </div>

        <div>
          <div className="card">
            <h2 style={{ marginBottom: '1.5rem', fontSize: '1.25rem' }}>Recent GCI Entries</h2>
            
            {gciEntries.length === 0 ? (
              <p style={{ color: 'var(--text-secondary)' }}>No GCI entries logged.</p>
            ) : (
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid var(--border-color)', textAlign: 'left' }}>
                    <th style={{ padding: '0.75rem', color: 'var(--text-secondary)', fontWeight: 500 }}>Month</th>
                    <th style={{ padding: '0.75rem', color: 'var(--text-secondary)', fontWeight: 500 }}>Team Agent</th>
                    <th style={{ padding: '0.75rem', color: 'var(--text-secondary)', fontWeight: 500 }}>Source Agent</th>
                    <th style={{ padding: '0.75rem', color: 'var(--text-secondary)', fontWeight: 500 }}>Amount</th>
                    <th style={{ padding: '0.75rem', color: 'var(--text-secondary)', fontWeight: 500, textAlign: 'right' }}>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {gciEntries.map(entry => (
                    <tr key={entry.id} style={{ borderBottom: '1px solid var(--border-color)' }}>
                      <td style={{ padding: '0.75rem' }}>
                        {new Date(entry.month).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}
                      </td>
                      <td style={{ padding: '0.75rem', fontWeight: 600, color: 'var(--primary)' }}>
                        {entry.teamAgent.name}
                      </td>
                      <td style={{ padding: '0.75rem' }}>
                        {entry.sourceAgent?.name || <span style={{ color: 'var(--text-secondary)' }}>N/A</span>}
                      </td>
                      <td style={{ padding: '0.75rem', fontWeight: 600 }}>
                        ${entry.amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                      </td>
                      <td style={{ padding: '0.75rem', textAlign: 'right' }}>
                        <AdminGciActions gci={entry} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
